---
- name: Add ssh public keys to user (directory)
  authorized_key:
    user: "{{ ssh_keys_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ ssh_keys_public_keys_dir }}/*"
  tags: ssh-keys, ssh-keys-add

- name: Add ssh public keys to user (vars)
  authorized_key:
    user: "{{ ssh_keys_user }}"
    key: "{{ item }}"
  with_items: "{{ ssh_keys_public_keys }}"
  tags: ssh-keys, ssh-keys-add

- name: Remove old ssh public keys from user (directory)
  authorized_key:
    user: "{{ ssh_keys_user }}"
    key: "{{ lookup('file', item) }}"
    state: absent
  with_fileglob: "{{ ssh_keys_public_keys_removed_dir }}/*"
  tags: ssh-keys, ssh-keys-remove

- name: Remove old ssh public keys from user (vars)
  authorized_key:
    user: "{{ ssh_keys_user }}"
    key: "{{ item }}"
    state: absent
  with_items: "{{ ssh_keys_public_keys_removed }}"
  tags: ssh-keys, ssh-keys-remove
